### ISSUE TITLE
Test scaffold idea

### ISSUE THREAD

**Issue by hyandell** [amzn/ion-tests#9]
Porting the unit test approach to every language is a bit of a pain when writing a new parser (I imagine).

It would be cool to have a basic scaffold that relies on the command line to execute the parser.

ie) perhaps you run:

```
run-ion-tests rust-ion-cmd
```

and in turn it takes the data and runs it through the rust-ion-parser with pre-accepted flags, ie:

```
rust-ion-cmd --assert-equal <ion-test-file1> <ion-test-file2>
rust-ion-cmd --assert-fail <ion-test-file1>
rust-ion-cmd --assert-pass <ion-test-file1>
rust-ion-cmd --assert-unequal <ion-test-file1> <ion-test-file2>
```

**Comment by almann** [comment]
Yes, this is a really good idea.

Basically I think it consists of a standard command line interface that serves as an API of sorts.  Some examples of the types of things we'd probably like to support (in addition to what's mentioned above):

* Intra-file equivalence and non-equivalence.
* Round-trip options. (e.g. input as text, output as binary)

The above can not only make automating testing easier, but allow for interesting cross-implementation testing.

**Comment by jonwilsdon** [comment]
This is completed in: https://github.com/amzn/ion-test-driver
